// front-end/react/full-stack-engineer-q2/src/App.js
import React from 'react';
import logo from './favicon.png';
import $ from 'jquery';
import './App.css';


function App() {
  // Wait for the DOM to be ready
  $(document).ready(function () {
    /**
     * Author: Ramon Jr. Yniguez
     * Purpose: Highligh, JQuery Knowlege and implementation
     * Date: Apr 16, 2020
     */
    const api = "http://localhost:23456/api";
    var apiJQueryRequestExample = function (data) {
      return fetch(`${api}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          'Username': data.Username,
          'Email': data.email,
          'Password': data.password,
          'cmPassword': data.cmpassword
        })
      }).then(function (result) {
        return result.json();
      });
    };
    // Initialize form validation on the form.
    $("form[name='userSignUpForm']").validate({
      wrapper: "div",
      // Specify validation rules
      rules: {
        // The key name on the left side is the name attribute
        // of an input field. Validation rules are defined
        // on the right side
        Username: {
          required: true,
          minlength: 5,
          maxlength: 15
        },
        Email: {
          required: true,
          // Specify that email should be validated
          // by the built-in "email" rule
          email: true,
          maxlength: 20,
        },
        Password: {
          required: true,
          minlength: 5,
          maxlength: 10,
        },
        cmPassword: {
          required: true,
          minlength: 5,
          maxlength: 10,
          equalTo: "#Password"
        },
      },
      // Specify validation error messages
      messages: {
        Username: {
          required: "Please provide Username",
          minlength: "Your Username must cannot be less than 5 or more than 15 characters long",
          maxlength: "Your Username must cannot be less than 5 or more than 15 characters long",
        },
        email: {
          required: "Please enter a valid email address",
          minlength: "Your password must be at least 5 characters long",
          maxlength: "Your password must be at least 20 characters long"
        },
        password: {
          required: "Please provide a password",
          minlength: "Your password must be at least 5 characters long",
          maxlength: "Your password must be at least 10 characters long"
        },
        cmPassword: {
          required: "Make sure it matches password",
        },
      },
      // fomr button handler
      submitHandler: function (form) {
        form.submit(); // <- use 'form' argument here.
      }
    });
    // validate form inputs
    $('form').find(':input').each(function (index, value) {
      /**
       * Author: Ramon Jr. Yiguez
       * Purpose: Traverse Form Inputs and validate, else disable button
       * Date: Apr 16, 2020
       */
      $(value).on('click', function () {
        if ($('form').valid()) {
          $("#userSignUpFormButton").prop('disabled', false);
          console.log('if Condition', value.validity.valid, $('form').valid());
        } else {
          $("#userSignUpFormButton").prop('disabled', true);
          console.log('else Condition', value.validity.valid, $('form').valid());
        }
      })
    })
    $(document.body).on('click', function (value) {
      if ($('form').valid()) {
        $("#userSignUpFormButton").prop('disabled', false);
        console.log('if Condition', value.valid, $('form').valid());
      } else {
        $("#userSignUpFormButton").prop('disabled', true);
        console.log('else Condition', value.valid, $('form').valid());
      }
      document.getElementById('userSignUpFormButton')
        .addEventListener('click', () => {
          /**
           * Author: Ramon Jr. Yiguez
           * Purpose: Register Event Listener for Button Click, and issue request based on BackEnd Selection
           * Date: Apr 16, 2020
           */
        })
    });
  });
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <a href="https://www.lightfeather.io">LightFeather.io</a>

        <h1>Full Stack Engineer Coding Challenge</h1>
        <br />
        <section>
          <div>
            <h4> <u>Question 2: Web Component Specifications</u></h4>
            <p>
              Create a User SignUp that accepts the following fields:
            </p>
            <ul>
              <li>
                Username
                </li>
              <li>
                Email
                </li>
              <li>
                Password
                </li>
              <li>
                Confirm Password
                </li>
            </ul>
          </div>
          <br />
          <div>
            <form action="./assets/php/login.php" method="post" name="userSignUpForm" autocomplete="off">
              <fieldset>
                <div>
                  <label for="Username">Username:</label>
                  <input maxlength="15" minlength="5" name="Username" type="text" id="Username" spellcheck="false"
                    pattern="^([- \w\d\u00c0-\u024f]+)$" autofocus required />
                </div>
                <div>
                  <label for="Email">Email:</label>
                  <input type="email" name="Email" id="Email" spellcheck="false"
                    pattern="^(([-\w\d]+)(\.[-\w\d]+)*@([-\w\d]+)(\.[-\w\d]+)*(\.([a-zA-Z]{2,5}|[\d]{1,3})){1,2})$"
                    autofocus required />
                </div>
                <div>
                  <label for="Passowrd">Password:</label>
                  <input minlength="5" name="Password" type="text" id="Password" autofocus required />
                </div>
                <div>
                  <label for="cmPassword">Confirm Password:</label>
                  <input minlength="5" name="cmPassword" type="text" id="cmPassword" autofocus required />
                </div>
                <div>
                  <button type="submit" id="userSignUpFormButton" disabled>Submit</button>
                </div>
              </fieldset>
            </form>
          </div>
        </section>
      </header>
    </div>
  );
}

export default App;

// front-end/Angular/full-stack-engineer-q2/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, FormControl, Validators, AbstractControl } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'full-stack-engineer-q2';
  formGroup: FormGroup;

  constructor(public formBuilder: FormBuilder) {

  }
  ngOnInit(): void {
    this.initForm();
    this.resetForm();
  }
  get userName(): any {
    return this.formGroup.get('Username');
  }
  get Email(): any {
    return this.formGroup.get('Email');
  }
  get Password(): any {
    return this.formGroup.get('Password');
  }
  get cmPassword(): any {
    return this.formGroup.get('cmPassword');
  }

  private cmpEntry(control: AbstractControl) {
    return control.value ? control.value !== this.cmPassword.value : false;
  }

  protected initForm(): FormGroup {
    return this.formGroup = this.formBuilder.group({
      Username: new FormControl('', Validators.compose([Validators.required,
      Validators.maxLength(15), Validators.minLength(5)])),
      Email: new FormControl('', Validators.compose([Validators.required, Validators.email])),
      Password: new FormControl('', Validators.compose([Validators.required,
      Validators.minLength(5), Validators.maxLength(5), this.cmpEntry.bind(this)])),
      cmPassword: new FormControl('', Validators.compose([Validators.required,
      Validators.minLength(5), Validators.maxLength(5), this.cmpEntry.bind(this)]))
    });
  }

  public onFormSubmit(): void {
    if (this.formGroup.invalid) {
      return;
    }
    console.log('this.formGroup.invalid', this.formGroup.value);
  }
  public resetForm(): void {
    return this.formGroup.reset();
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<h1>Full Stack Engineer Coding Challenge</h1>
<br />
<div id="lightfeather"></div>
<div>
  <a href="https://www.lightfeather.io">LightFeather.io</a>
</div>
<br />
<section class="fadeIn">
  <div>
    <h4> <u>Question 2: Web Component Specifications</u></h4>
    <p>
      Create a User SignUp that accepts the following fields:
    </p>
    <ul>
      <li>
        Username
      </li>
      <li>
        Email
      </li>
      <li>
        Password
      </li>
      <li>
        Confirm Password
      </li>
    </ul>
  </div>
  <br />
  <div>
    <form [formGroup]="formGroup" name="userSignUpForm" (ngSubmit)="onFormSubmit()">
      <fieldset>
        <div>
          <label for="Username">Username:</label>
          <input formControlName="Username" maxlength="15" minlength="5" name="Username" type="text" id="Username"
            spellcheck="false" pattern="^([- \w\d\u00c0-\u024f]+)$" autofocus required>
          <div *ngIf="userName.invalid && (userName.dirty || userName.touched)">
            <div *ngIf="userName.errors.required">
              UserName is required.
            </div>
            <div *ngIf="userName.errors.maxlength">
              UserName cannot be more than 15 characters long.
            </div>
            <div *ngIf="userName.errors.minlength">
              UserName must be at least 5 characters long.
            </div>
          </div>
        </div>
        <div>
          <label for="Email">Email:</label>
          <input formControlName="Email" type="email" name="Email" id="Email" spellcheck="false"
            pattern="^(([-\w\d]+)(\.[-\w\d]+)*@([-\w\d]+)(\.[-\w\d]+)*(\.([a-zA-Z]{2,5}|[\d]{1,3})){1,2})$" autofocus
            required />
          <div *ngIf="Email.invalid && (Email.dirty || Email.touched)">
            <div *ngIf="Email.errors.required">
              Email is required.
            </div>
            <div *ngIf="Email.errors.email">
              Please provide a valid email
            </div>
          </div>
        </div>
        <div>
          <label for="Passowrd">Password:</label>
          <input formControlName="Password" minlength="5" name="Password" type="text" id="Password" autofocus required>
          <div *ngIf="Password.invalid && (Password.dirty || Password.touched)">
            <div *ngIf="Password.errors.required">
              Password is required.
            </div>
            <div *ngIf="Password.errors.maxlength">
              Password cannot be more than 10 characters long.
            </div>
            <div *ngIf="Password.errors.minlength">
              Password must be at least 5 characters long.
            </div>
          </div>
        </div>
        <div>
          <label for="cmPassword">Confirm Password:</label>
          <input formControlName="cmPassword" minlength="5" name="cmPassword" type="text" id="cmPassword" autofocus
            required>
          <div
            *ngIf="cmPassword.invalid && (cmPassword.dirty || cmPassword.touched) || Password.value !== cmPassword.value">
            <div *ngIf="cmPassword.errors.required">
              Please confirm password
            </div>
            <div *ngIf="cmPassword.errors.maxlength">
              Password cannot be more than 10 characters long.
            </div>
            <div *ngIf="cmPassword.errors.minlength">
              Password must be at least 5 characters long.
            </div>
            <div *ngIf="Password.value !== cmPassword.value">
              Password does not match {{Password.value}}
            </div>
          </div>
        </div>
        <div>
          <button type="submit" id="userSignUpFormButton" [disabled]="formGroup.invalid">Submit</button>
        </div>
      </fieldset>
    </form>
  </div>
</section>

<router-outlet></router-outlet>
